---
title: "Challenge 2"
author: "Shuqi Hong"
description: "Data wrangling: using group() and summarise()"
date: "6/6/2023"
format:
  html:
    toc: true
    code-fold: true
    code-copy: true
    code-tools: true
categories:
  - challenge_2
  - railroads
  - faostat
  - hotel_bookings
---

```{r}
#| label: setup
#| warning: false
#| message: false

library(tidyverse)
library(readr)
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)

```

Here are the analysis for railroad file.
```{r}
rr <- read_csv("_data/railroad_2012_clean_county.csv")

#discard county and group others
rr2 <- rr %>% select(state,total_employees) %>% group_by(state) 

rr3 <- rr %>% select(state,total_employees)

#Find mode function
compute_mode <- function(x){
  mode_index <- which.max(table(x))
  mode <- x[mode_index]
return(mode)
}

#Calculate central tendency and dispersion for each state
rr2 %>%
  summarise(mean_employees=mean(total_employees),median_employees=median(total_employees), mode_employees=compute_mode(total_employees), iqr_employees=IQR(total_employees), sd_employees = sd(total_employees) , min_employees=min(total_employees), max_employees=max(total_employees)) 

#Calculate central tendency and dispersion for all states
rr3 %>%
  summarise(mean_employees=mean(total_employees),median_employees=median(total_employees), mode_employees=compute_mode(total_employees),iqr_employees=IQR(total_employees), sd_employees = sd(total_employees) , min_employees=min(total_employees), max_employees=max(total_employees)) 

#Filter out the number of employees of each county in AK
rr%>% filter(`state`=="AK")
```

Here are the analysis for hotel data
```{r}
hb <- read_csv("_data/hotel_bookings.csv")

#See the name of each colunm
colnames(hb)

#See what kind of hotel names there are
unique(hb$hotel)

#Change the name of is_canceled which is not clear to see
hb <- hb %>% 
  mutate(state = case_when
         (is_canceled == "1" ~ "canceled",
          is_canceled == "0" ~ "regular"))

#make a new table for each hotel
CityHotel <-hb %>% filter(`hotel` == "City Hotel")
CityHotel

ResortHotel <-hb %>% filter(`hotel` == "Resort Hotel")
ResortHotel
```
```{r}
#Make a corsstable
comparison_hs <-xtabs(~hotel+state, hb)
comparison_hs

comparison_hc <-xtabs(~hotel+children, hb)
comparison_hc

rowSums(comparison_hc)
```
From this new table, we can compare the number of cancel state of two hotel.

```{r}

hb<- hb %>% mutate(`customer number` =adults + babies + children)
head(hb)

hb %>% select(country,"customer number", hotel) %>% 
  pivot_wider(names_from=country, values_from="customer number")

```
I don't know why the cell became <dbl[123]>. Maybe I still don't know the meaning of pivot_wider. I mean what does it mean to swap columns and rows?
